clean:
	rm -rf ../output/FeaturesAnalysis/Histograms/*.png || true
	rm -rf ../output/FeaturesAnalysis/Heatmaps/*.png || true
	rm -rf ../output/DimensionalityReduction/PCA/*.png || true
	rm -rf ../output/DimensionalityReduction/LDA/*.png || true
	rm -rf ../output/Training/*.txt || true
	rm -rf ./modules/__pycache__ || true
	rm ./tmp.txt || true
	clear

run:
	python3 main.py
	clear
	