clean:
	rm ../output/00_histograms/*.png
	rm ../output/01_heatmaps/*.png
	rm ../output/02_PCA/*.png
	rm ../output/03_LDA/*.png
	rm ../output/04_Kfold/*.txt
	rm ../output/05_DCF/*.txt
	clear

run:
	python3 main.py
	#clear
	